apiVersion: v1
kind: Service
metadata:
  name: budget-robinhood-server
spec:
  selector:
    app: budget-robinhood
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 6000
    # Port to forward to inside the pod
    targetPort: 5000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-robinhood-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-robinhood
  template:
    metadata:
      labels:
        app: budget-robinhood
    spec:
      containers:
      - name: budget-robinhood
        image: sticksword/budget-robinhood-server:0.5
        ports:
        - containerPort: 5000